<?php

namespace Coinsbank\Constant;

/**
 * Class CoinsbankTransactionType
 *
 * @package Coinsbank\Constant
 */
class CoinsbankTransactionType
{
    /**
     * Types
     */
    const TYPE_TRADE_COMMISSION = 3;
    const TYPE_TRADE_TRANSACTION_FEE = 4;
    const TYPE_TRADE = 5;
    const TYPE_TRADE_HOLD = 7;
    const TYPE_TRADE_HOLD_CANCELLED = 8;

    const TYPE_PAYMENTS_WITHDRAWAL = 10;
    const TYPE_PAYMENTS_DEPOSIT = 11;
    const TYPE_PAYMENTS_DEPOSIT_COMMISSION = 13;
    const TYPE_PAYMENTS_WITHDRAWAL_COMMISSION = 14;
    const TYPE_PAYMENTS_SYSTEM_DEPOSIT = 15;
    const TYPE_PAYMENTS_SYSTEM_WITHDRAWAL = 17;

    const TYPE_TRANSFER_FUNDS_TO_SELF = 20;
    const TYPE_TRANSFER_FUNDS_TO_OTHER = 21;
    const TYPE_TRANSFER_COMMISSION = 23;
    const TYPE_TRANSFER_COMMISSION_CONVERT = 24;
    const TYPE_TRANSFER_GIFT = 25;
    const TYPE_TRANSFER_FUNDS_TO_SELF_RECEIVE = 26;
    const TYPE_TRANSFER_FUNDS_TO_OTHER_RECEIVE = 27;

    const TYPE_GIFT_APPLY = 42;
    const TYPE_GIFT_ONETIME = 43;

    const TYPE_CARD_HOLD = 52;
    const TYPE_CARD_PARTNER_TRANSFER = 53;
    const TYPE_CARD_ISSUANCE = 54;
    const TYPE_CARD_COMMISSION_CARD_DELIVERY = 55;
    const TYPE_CARD_ISSUANCE_EMBOSS = 56;
    const TYPE_CARD_CANCEL = 57;
    const TYPE_CARD_COMMISSION_CARD_ISSUE = 58;
    const TYPE_CARD_PROCESS = 59;
    const TYPE_CARD_COMMISSION_COINSBANK = 60;
    const TYPE_CARD_COMMISSION_MAINTENANCE = 61;
    const TYPE_CARD_COMMISSION_COINSBANK_FIXED = 62;
    const TYPE_CARD_ACTIVATE = 63;
    const TYPE_CARD_PAYMENT_CONVERT = 64;
    const TYPE_CARD_REVERSAL = 65;
    const TYPE_CARD_REFUND = 66;
    const TYPE_CARD_INSURANCE = 67;
    const TYPE_CARD_COMMISSION_CONVERT = 68;

    const TYPE_PAYMENTS_CASHBACK = 69;
    const TYPE_COMMISSION_CANCEL = 70;

    const TYPE_CARD_EXPIRE = 71;
    const TYPE_CARD_CLOSED = 72;
    const TYPE_CARD_COMMISSION_DEPOSIT = 73;
    const TYPE_CARD_COMMISSION_DELETE = 74;

    const TYPE_USER_COMMISSION_DELETE = 75;
    const TYPE_MERCHANT_COMMISSION = 76;
    const TYPE_MERCHANT_PAYMENT_CONVERT = 77;
    const TYPE_MERCHANT_PAYMENT = 78;
    const TYPE_SMS_COMMISSION = 79;
    const TYPE_CARD_MONTHLY_COMMISSION = 80;
    const TYPE_DEPOSIT_CHARGEBACK = 81;
    const TYPE_DEPOSIT_COMMISSION_CHARGEBACK = 82;

    /**
     * Type groups.
     */
    const TYPE_GROUP_TRADE = 1;
    const TYPE_GROUP_DEPOSIT = 2;
    const TYPE_GROUP_WITHDRAWAL = 3;
    const TYPE_GROUP_CARD = 5;
    const TYPE_GROUP_USER = 6;
    const TYPE_GROUP_MERCHANT = 7;
}